# .github/workflows/deploy.yml
name: Deploy Node Static Site to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: testno1
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
